### ISSUE TITLE
No modded resourcepacks on Quilt

### ISSUE THREAD

**Issue by SplendidAlakey** [enjarai/recursive-resources#25]
**MC** 1.19.2
**[Extended Drawers](https://modrinth.com/mod/extended-drawers)** 1.3.10
**Recursive Resources** 2.4.2

To reproduce the crash simply install Extended Drawers and Recursive Resources, launch the game and open the resourcepacks page.

Logs: https://gist.github.com/SplendidAlakey/775559cddd7d8d06f7cd7e077f62bd49#file-crash-log
https://gist.github.com/SplendidAlakey/775559cddd7d8d06f7cd7e077f62bd49#file-latest-log

To reproduce the missing modded resourcepacks on Quilt, install the same mods on Quilt and replace FAPI with QSL, then open the resourcepacks page.

![2023-05-15_10 12 58](https://github.com/enjarai/recursive-resources/assets/86702831/542d78cd-4391-4a51-931f-247906828270)

Logs: https://gist.github.com/SplendidAlakey/775559cddd7d8d06f7cd7e077f62bd49#file-latest_quilt-log

**Comment by enjarai** [comment]
The builtin resourcepacks from Extended Drawers apparently contain ":", which is an illegal path character, and caused a crash. I've fixed this issue and added some more robust error handling with update 2.4.3, which is publishing now, so this shouldn't happen again.

This update also includes a bit of extra logging for packs that arent being processed properly, which should help me find the issue with Quilt. Could you send another Quilt log using the new update?

**Comment by SplendidAlakey** [comment]
Sorry for a delayed response, here's the new Quilt logs: https://gist.github.com/SplendidAlakey/92c0a3d64d32cd54311ff40102f23031

I can also confirm, that the crash has been fixed.

**Comment by MenacingPerson** [comment]
I hate to be that guy... but... this is still happening, so any fix?
